language: node_js
node_js:
  - "4"
  - "5"
  - "6"
  - "7"
  - "8"
dist: trusty
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: "(npm test || npm test) && sudo sh -c 'export PATH=\"'\"$(dirname $(which node)):$PATH\"'\" && npm run test:root && npm run test:install'"
before_script:
  - "./test/hosts.sh"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq graphicsmagick
  - npm install -g npm@5
after_script:
  - npm run test:report-coverage
notifications:
  email: false
  webhooks:
    - https://pumabot.strugee.net/hubot/travis-ci-events
