language: node_js
node_js:
  - "0.10"
  - "0.12"
  - "4"
  - "6"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: "npm test && sudo sh -c 'export PATH=\"'\"$(dirname $(which node)):$PATH\"'\" && npm run test-root' && npm run test:install"
before_script:
  - "./test/hosts.sh"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq graphicsmagick
notifications:
 email: false
 irc:
   channels:
     - "chat.freenode.net#pump.io"
   on_success: change
   on_failure: change
