language: node_js
node_js:
  - 0.8
script: "./node_modules/.bin/vows --spec test/*-test.js; sudo /usr/bin/nodejs ./node_modules/.bin/vows --spec test/*-test-as-root.js"
before_script: 
  - "./test/hosts.sh"

